"""empty message

Revision ID: 36bb0e6da435
Revises: bff73a2bf7a6
Create Date: 2020-04-14 15:52:25.285036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36bb0e6da435'
down_revision = 'bff73a2bf7a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movie', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='unique')
    # ### end Alembic commands ###
