"""empty message

Revision ID: 62fdaea26a70
Revises: 5b0ff80557b8
Create Date: 2020-04-11 18:28:02.761306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fdaea26a70'
down_revision = '5b0ff80557b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('actor')
    op.create_unique_constraint(None, 'movie', ['title'])
    op.drop_constraint('movie_actor_id_fkey', 'movie', type_='foreignkey')
    op.drop_column('movie', 'actor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('actor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('movie_actor_id_fkey', 'movie', 'actor', ['actor_id'], ['id'])
    op.drop_constraint(None, 'movie', type_='unique')
    op.create_table('actor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='actor_pkey')
    )
    # ### end Alembic commands ###
