"""empty message

Revision ID: 6f44fff33dab
Revises: b862427bb28e
Create Date: 2020-04-15 09:57:55.554370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f44fff33dab'
down_revision = 'b862427bb28e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movie', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='unique')
    # ### end Alembic commands ###
