"""empty message

Revision ID: 72fb4f069f4d
Revises: 62fdaea26a70
Create Date: 2020-04-11 18:30:15.383041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72fb4f069f4d'
down_revision = '62fdaea26a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movie', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='unique')
    # ### end Alembic commands ###
