"""empty message

Revision ID: 82399156088f
Revises: 36bb0e6da435
Create Date: 2020-04-14 20:44:44.989480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82399156088f'
down_revision = '36bb0e6da435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'movie', ['title'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='unique')
    # ### end Alembic commands ###
