"""empty message

Revision ID: bff73a2bf7a6
Revises: 47582462a4fd
Create Date: 2020-04-14 11:19:47.861739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bff73a2bf7a6'
down_revision = '47582462a4fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('actor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'movie', 'actor', ['actor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_column('movie', 'actor_id')
    # ### end Alembic commands ###
