"""Initial migration.

Revision ID: ce998f971436
Revises: d305a73fcdba
Create Date: 2020-04-09 12:04:51.165032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce998f971436'
down_revision = 'd305a73fcdba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('genre', sa.String(), nullable=True))
    op.add_column('Movies', sa.Column('length', sa.Float(), nullable=True))
    op.add_column('Movies', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('Movies', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Movies', 'name')
    op.drop_column('Movies', 'length')
    op.drop_column('Movies', 'genre')
    # ### end Alembic commands ###
