"""Initial migration.

Revision ID: d305a73fcdba
Revises: 577502d2f2de
Create Date: 2020-04-09 12:02:50.174921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd305a73fcdba'
down_revision = '577502d2f2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('title', sa.String(), nullable=True))
    op.drop_column('Movies', 'genre')
    op.drop_column('Movies', 'name')
    op.drop_column('Movies', 'length')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('length', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('Movies', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Movies', sa.Column('genre', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Movies', 'title')
    # ### end Alembic commands ###
